package Capa_Presentacion;


import java.awt.BorderLayout;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author cedre
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        
        
        
    }
    
    private void ShowPanel(JPanel p){
        p.setSize(642, 559);
        p.setLocation(0,0);
        
        Content.removeAll();
        Content.add(p,BorderLayout.CENTER);
        Content.revalidate();
        Content.repaint();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbAltaPerfil = new javax.swing.JButton();
        jbAltaGenero = new javax.swing.JButton();
        jbAltaAlbum = new javax.swing.JButton();
        jbCrearLista = new javax.swing.JButton();
        jbAgregarTema = new javax.swing.JButton();
        jbQuitarTema = new javax.swing.JButton();
        jbPublicarLista = new javax.swing.JButton();
        jbSeguirUsuario = new javax.swing.JButton();
        jbDejarSeguirU = new javax.swing.JButton();
        jbGuardarTLA = new javax.swing.JButton();
        jbEliminarTLA = new javax.swing.JButton();
        jbConsultarPerfil = new javax.swing.JButton();
        jbConsultarAlbum = new javax.swing.JButton();
        jbConsultarLista = new javax.swing.JButton();
        Logo = new javax.swing.JLabel();
        Content = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));

        jbAltaPerfil.setBackground(new java.awt.Color(0, 204, 102));
        jbAltaPerfil.setForeground(new java.awt.Color(0, 0, 0));
        jbAltaPerfil.setText("Alta Perfil");
        jbAltaPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaPerfilActionPerformed(evt);
            }
        });

        jbAltaGenero.setBackground(new java.awt.Color(0, 204, 102));
        jbAltaGenero.setForeground(new java.awt.Color(0, 0, 0));
        jbAltaGenero.setText("Alta Genero");
        jbAltaGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaGeneroActionPerformed(evt);
            }
        });

        jbAltaAlbum.setBackground(new java.awt.Color(0, 204, 102));
        jbAltaAlbum.setForeground(new java.awt.Color(0, 0, 0));
        jbAltaAlbum.setText("Alta Album");
        jbAltaAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAltaAlbumActionPerformed(evt);
            }
        });

        jbCrearLista.setBackground(new java.awt.Color(0, 204, 102));
        jbCrearLista.setForeground(new java.awt.Color(0, 0, 0));
        jbCrearLista.setText("Crear Lista");
        jbCrearLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCrearListaActionPerformed(evt);
            }
        });

        jbAgregarTema.setBackground(new java.awt.Color(0, 204, 102));
        jbAgregarTema.setForeground(new java.awt.Color(0, 0, 0));
        jbAgregarTema.setText("Agregar Temas a Lista");
        jbAgregarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAgregarTemaActionPerformed(evt);
            }
        });

        jbQuitarTema.setBackground(new java.awt.Color(0, 204, 102));
        jbQuitarTema.setForeground(new java.awt.Color(0, 0, 0));
        jbQuitarTema.setText("Quitar Temas a Lista");
        jbQuitarTema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbQuitarTemaActionPerformed(evt);
            }
        });

        jbPublicarLista.setBackground(new java.awt.Color(0, 204, 102));
        jbPublicarLista.setForeground(new java.awt.Color(0, 0, 0));
        jbPublicarLista.setText("Publicar Lista");
        jbPublicarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPublicarListaActionPerformed(evt);
            }
        });

        jbSeguirUsuario.setBackground(new java.awt.Color(0, 204, 102));
        jbSeguirUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jbSeguirUsuario.setText("Seguir Usuario");
        jbSeguirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSeguirUsuarioActionPerformed(evt);
            }
        });

        jbDejarSeguirU.setBackground(new java.awt.Color(0, 204, 102));
        jbDejarSeguirU.setForeground(new java.awt.Color(0, 0, 0));
        jbDejarSeguirU.setText("Dejar de Seguir Usuario");
        jbDejarSeguirU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDejarSeguirUActionPerformed(evt);
            }
        });

        jbGuardarTLA.setBackground(new java.awt.Color(0, 204, 102));
        jbGuardarTLA.setForeground(new java.awt.Color(0, 0, 0));
        jbGuardarTLA.setText("Guardar T/L/A");
        jbGuardarTLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarTLAActionPerformed(evt);
            }
        });

        jbEliminarTLA.setBackground(new java.awt.Color(0, 204, 102));
        jbEliminarTLA.setForeground(new java.awt.Color(0, 0, 0));
        jbEliminarTLA.setText("Eliminar T/L/A");
        jbEliminarTLA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarTLAActionPerformed(evt);
            }
        });

        jbConsultarPerfil.setBackground(new java.awt.Color(0, 204, 102));
        jbConsultarPerfil.setForeground(new java.awt.Color(0, 0, 0));
        jbConsultarPerfil.setText("Consultar Perfil");
        jbConsultarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarPerfilActionPerformed(evt);
            }
        });

        jbConsultarAlbum.setBackground(new java.awt.Color(0, 204, 102));
        jbConsultarAlbum.setForeground(new java.awt.Color(0, 0, 0));
        jbConsultarAlbum.setText("Consultar Album");
        jbConsultarAlbum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarAlbumActionPerformed(evt);
            }
        });

        jbConsultarLista.setBackground(new java.awt.Color(0, 204, 102));
        jbConsultarLista.setForeground(new java.awt.Color(0, 0, 0));
        jbConsultarLista.setText("Consultar Lista");
        jbConsultarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbConsultarListaActionPerformed(evt);
            }
        });

        Logo.setBackground(new java.awt.Color(0, 0, 0));
        Logo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Logo.setForeground(new java.awt.Color(0, 204, 102));
        Logo.setText("Espotify");

        Content.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout ContentLayout = new javax.swing.GroupLayout(Content);
        Content.setLayout(ContentLayout);
        ContentLayout.setHorizontalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        ContentLayout.setVerticalGroup(
            ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(Logo))
                    .addComponent(jbAltaPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAltaGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAltaAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbCrearLista, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAgregarTema, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbQuitarTema, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbPublicarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSeguirUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDejarSeguirU)
                    .addComponent(jbGuardarTLA, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminarTLA, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsultarPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsultarAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbConsultarLista, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(Logo)
                .addGap(6, 6, 6)
                .addComponent(jbAltaPerfil)
                .addGap(6, 6, 6)
                .addComponent(jbAltaGenero)
                .addGap(6, 6, 6)
                .addComponent(jbAltaAlbum)
                .addGap(6, 6, 6)
                .addComponent(jbCrearLista)
                .addGap(6, 6, 6)
                .addComponent(jbAgregarTema)
                .addGap(6, 6, 6)
                .addComponent(jbQuitarTema)
                .addGap(6, 6, 6)
                .addComponent(jbPublicarLista)
                .addGap(6, 6, 6)
                .addComponent(jbSeguirUsuario)
                .addGap(6, 6, 6)
                .addComponent(jbDejarSeguirU)
                .addGap(6, 6, 6)
                .addComponent(jbGuardarTLA)
                .addGap(6, 6, 6)
                .addComponent(jbEliminarTLA)
                .addGap(6, 6, 6)
                .addComponent(jbConsultarPerfil)
                .addGap(6, 6, 6)
                .addComponent(jbConsultarAlbum)
                .addGap(6, 6, 6)
                .addComponent(jbConsultarLista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(Content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Content.getAccessibleContext().setAccessibleParent(this);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAltaPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaPerfilActionPerformed
        IAltaPerfil p = new IAltaPerfil();
        ShowPanel(p);
    }//GEN-LAST:event_jbAltaPerfilActionPerformed

    private void jbAltaGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaGeneroActionPerformed
        IAltaGenero p = new IAltaGenero();
        ShowPanel(p);
    }//GEN-LAST:event_jbAltaGeneroActionPerformed

    private void jbAltaAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAltaAlbumActionPerformed
        IAltaAlbum p = new IAltaAlbum();
        ShowPanel(p);
    }//GEN-LAST:event_jbAltaAlbumActionPerformed

    private void jbCrearListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCrearListaActionPerformed
        ICrearLista p = new ICrearLista();
        ShowPanel(p);
    }//GEN-LAST:event_jbCrearListaActionPerformed

    private void jbAgregarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAgregarTemaActionPerformed
        IAgregarTema p = new IAgregarTema();
        ShowPanel(p);
    }//GEN-LAST:event_jbAgregarTemaActionPerformed

    private void jbQuitarTemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbQuitarTemaActionPerformed
        IQuitarTema p = new IQuitarTema();
        ShowPanel(p);
    }//GEN-LAST:event_jbQuitarTemaActionPerformed

    private void jbPublicarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPublicarListaActionPerformed
        IPublicarLista p = new IPublicarLista();
        ShowPanel(p);
    }//GEN-LAST:event_jbPublicarListaActionPerformed

    private void jbSeguirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSeguirUsuarioActionPerformed
        ISeguirUsr p = new ISeguirUsr();
        ShowPanel(p);
    }//GEN-LAST:event_jbSeguirUsuarioActionPerformed

    private void jbDejarSeguirUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDejarSeguirUActionPerformed
        IDejarDeSeguirUsuario p = new IDejarDeSeguirUsuario();
        ShowPanel(p);
    }//GEN-LAST:event_jbDejarSeguirUActionPerformed

    private void jbGuardarTLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarTLAActionPerformed
        IGuardarTLA p = new IGuardarTLA();
        ShowPanel(p);
    }//GEN-LAST:event_jbGuardarTLAActionPerformed

    private void jbEliminarTLAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarTLAActionPerformed
        IEliminarTLA p = new IEliminarTLA();
        ShowPanel(p);
    }//GEN-LAST:event_jbEliminarTLAActionPerformed

    private void jbConsultarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarPerfilActionPerformed
        IConsultarPerfil p = new IConsultarPerfil();
        ShowPanel(p);
    }//GEN-LAST:event_jbConsultarPerfilActionPerformed

    private void jbConsultarAlbumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarAlbumActionPerformed
        IConsultarAlbum p = new IConsultarAlbum();
        ShowPanel(p);
    }//GEN-LAST:event_jbConsultarAlbumActionPerformed

    private void jbConsultarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbConsultarListaActionPerformed
        IConsultarLista p = new IConsultarLista();
        ShowPanel(p);
    }//GEN-LAST:event_jbConsultarListaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Content;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAgregarTema;
    private javax.swing.JButton jbAltaAlbum;
    private javax.swing.JButton jbAltaGenero;
    private javax.swing.JButton jbAltaPerfil;
    private javax.swing.JButton jbConsultarAlbum;
    private javax.swing.JButton jbConsultarLista;
    private javax.swing.JButton jbConsultarPerfil;
    private javax.swing.JButton jbCrearLista;
    private javax.swing.JButton jbDejarSeguirU;
    private javax.swing.JButton jbEliminarTLA;
    private javax.swing.JButton jbGuardarTLA;
    private javax.swing.JButton jbPublicarLista;
    private javax.swing.JButton jbQuitarTema;
    private javax.swing.JButton jbSeguirUsuario;
    // End of variables declaration//GEN-END:variables
}
