package Capa_Presentacion;

import Logica.Factory;
import Logica.ICtrl;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author cedre
 */
public class IAgregarTema extends javax.swing.JPanel {

    /**
     * Creates new form IAltaPerfil
     */
    Factory fabric =Factory.getInstance();
    ICtrl ctrl = fabric.getICtrl();
    public IAgregarTema() {
        initComponents();
        Text1.setText("Tipo de Lista");
        jComboBox1.addItem("Particular");
        jComboBox1.addItem("Por Defecto");
        Text3.setText("Listas");
        Text4.setText("Temas");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text1 = new javax.swing.JLabel();
        ACEPTAR = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        Text2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Text3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        Text4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text1.setForeground(new java.awt.Color(255, 255, 255));
        Text1.setText("Text1");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 260, 20));

        ACEPTAR.setBackground(new java.awt.Color(0, 204, 102));
        ACEPTAR.setText("ACEPTAR");
        ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPTARActionPerformed(evt);
            }
        });
        add(ACEPTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 260, -1));

        Text2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setText("Text2");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 260, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 260, -1));

        Text3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text3.setForeground(new java.awt.Color(255, 255, 255));
        Text3.setText("Text3");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 260, 20));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 260, -1));

        Text4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text4.setForeground(new java.awt.Color(255, 255, 255));
        Text4.setText("Text4");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 260, 20));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 260, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        Object selectedItem1 = jComboBox1.getSelectedItem();
        //Object selectedItem2 = jComboBox2.getSelectedItem();
        String GoC = jComboBox2.getSelectedItem() != null ? jComboBox2.getSelectedItem().toString() : "";
        if("Particular".equals(selectedItem1)){
            if(jComboBox3.getItemCount() > 0){
                jComboBox3.removeAllItems();
            }
            for (String Part : ctrl.obtenerNombresDeListPart((String) GoC)) {
                    jComboBox3.addItem(Part);
            }
        }else{
            if(jComboBox3.getItemCount() > 0){
                jComboBox3.removeAllItems();
            }
            for (String PD : ctrl.obtenerNombresDeListPD((String) GoC)) {
                    jComboBox3.addItem(PD);
            }
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        //Particular o porDefecto
        Object selectedItem = jComboBox1.getSelectedItem();
        if("Particular".equals(selectedItem)){
            Text2.setText("Clientes");
            if(jComboBox2.getItemCount() > 0){
                jComboBox2.removeAllItems();
            }
            //Agregar nombres de los clientes
             for (String cli : ctrl.obtenerNombresDeCliente()) {
                    jComboBox2.addItem(cli);
            }
        }else{
            Text2.setText("Generos");
            if(jComboBox2.getItemCount() > 0){
                jComboBox2.removeAllItems();
            }
            //Agregar nombres de los Generos
            for (String genero : ctrl.obtenerNombresDeGeneros()) {
                if(!"Genero".equals(genero)){
                    jComboBox2.addItem(genero);
                }
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ACEPTARActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        Object selectedItem1 = jComboBox1.getSelectedItem();
        Object selectedItem2 = jComboBox2.getSelectedItem();
        if("Particular".equals(selectedItem1)){
            if(jComboBox4.getItemCount() > 0){
                jComboBox4.removeAllItems();
            }            
            for (String tem : ctrl.obtenerNombresTemaParaPartADD((String) selectedItem1, (String) selectedItem2)) {
                jComboBox4.addItem(tem);
            }
        }else{
            if(jComboBox4.getItemCount() > 0){
                jComboBox4.removeAllItems();
            }
            for (String tem : ctrl.obtenerNombresTemaParaPDADD((String) selectedItem1, (String) selectedItem2)) {
                jComboBox4.addItem(tem);
            }
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    // End of variables declaration//GEN-END:variables
}
