package Capa_Presentacion;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author cedre
 */
public class IAltaPerfil extends javax.swing.JPanel {

    /**
     * Creates new form IAltaPerfil
     */
    public IAltaPerfil() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text1 = new javax.swing.JLabel();
        TextField1 = new javax.swing.JTextField();
        Text2 = new javax.swing.JLabel();
        TextField2 = new javax.swing.JTextField();
        Text3 = new javax.swing.JLabel();
        TextField3 = new javax.swing.JTextField();
        Text4 = new javax.swing.JLabel();
        TextField4 = new javax.swing.JTextField();
        Text5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        Text6 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        TextField6 = new javax.swing.JTextField();
        Text7 = new javax.swing.JLabel();
        Text8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TextArea1 = new javax.swing.JTextArea();
        ACEPTAR = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text1.setForeground(new java.awt.Color(255, 255, 255));
        Text1.setText("Text1");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 310, 20));

        TextField1.setBackground(new java.awt.Color(102, 102, 102));
        TextField1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextField1.setForeground(new java.awt.Color(255, 255, 255));
        TextField1.setText("TextField1");
        TextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField1ActionPerformed(evt);
            }
        });
        add(TextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 310, 20));

        Text2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setText("Text2");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 310, 20));

        TextField2.setBackground(new java.awt.Color(102, 102, 102));
        TextField2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextField2.setForeground(new java.awt.Color(255, 255, 255));
        TextField2.setText("TextField2");
        TextField2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField2ActionPerformed(evt);
            }
        });
        add(TextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 310, 20));

        Text3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text3.setForeground(new java.awt.Color(255, 255, 255));
        Text3.setText("Text3");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 310, 20));

        TextField3.setBackground(new java.awt.Color(102, 102, 102));
        TextField3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextField3.setForeground(new java.awt.Color(255, 255, 255));
        TextField3.setText("TextField3");
        TextField3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField3ActionPerformed(evt);
            }
        });
        add(TextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 310, 20));

        Text4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text4.setForeground(new java.awt.Color(255, 255, 255));
        Text4.setText("Text4");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 310, 20));

        TextField4.setBackground(new java.awt.Color(102, 102, 102));
        TextField4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextField4.setForeground(new java.awt.Color(255, 255, 255));
        TextField4.setText("TextField4");
        TextField4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField4ActionPerformed(evt);
            }
        });
        add(TextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 310, 20));

        Text5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text5.setForeground(new java.awt.Color(255, 255, 255));
        Text5.setText("Text5");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 310, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 110, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 90, -1));

        Text6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text6.setForeground(new java.awt.Color(255, 255, 255));
        Text6.setText("Text6");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 310, 20));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        TextField6.setBackground(new java.awt.Color(102, 102, 102));
        TextField6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextField6.setForeground(new java.awt.Color(255, 255, 255));
        TextField6.setText("TextField6");
        TextField6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField6ActionPerformed(evt);
            }
        });
        add(TextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, 310, 20));

        Text7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text7.setForeground(new java.awt.Color(255, 255, 255));
        Text7.setText("Text7");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 310, 20));

        Text8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text8.setForeground(new java.awt.Color(255, 255, 255));
        Text8.setText("Text8");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 310, 20));

        TextArea1.setBackground(new java.awt.Color(102, 102, 102));
        TextArea1.setColumns(20);
        TextArea1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextArea1.setForeground(new java.awt.Color(255, 255, 255));
        TextArea1.setRows(5);
        jScrollPane6.setViewportView(TextArea1);

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 310, 110));

        ACEPTAR.setBackground(new java.awt.Color(0, 204, 102));
        ACEPTAR.setForeground(new java.awt.Color(0, 0, 0));
        ACEPTAR.setText("ACEPTAR");
        add(ACEPTAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField1ActionPerformed

    private void TextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField2ActionPerformed

    private void TextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField3ActionPerformed

    private void TextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField4ActionPerformed

    private void TextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField6ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JTextArea TextArea1;
    private javax.swing.JTextField TextField1;
    private javax.swing.JTextField TextField2;
    private javax.swing.JTextField TextField3;
    private javax.swing.JTextField TextField4;
    private javax.swing.JTextField TextField6;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
