package Capa_Presentacion;

import Logica.Factory;
import Logica.ICtrl;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.FlowLayout;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author cedre
 */
public class IConsultarLista extends javax.swing.JPanel {
    Factory fabric =Factory.getInstance();
    ICtrl ctrl = fabric.getICtrl();
    /**
     * Creates new form IAltaPerfil
     */
    public IConsultarLista() {
        initComponents();
        Text1.setVisible(false);
        Text2.setVisible(false);
        Text3.setVisible(false);
        Text4.setVisible(false);
        Text5.setVisible(false);
        Text6.setVisible(false);
        jButton1.setVisible(false);
        jButton1.setText("Seleccionar");
        jComboBox1.removeAllItems();
        jComboBox2.removeAllItems();
        jComboBox3.removeAllItems();
        jComboBox1.setVisible(false);
        jComboBox2.setVisible(false);
        jComboBox3.setVisible(false);
        jPanel1.setVisible(false);
        
        Text1.setText("Filtrar por:");
        
        jComboBox1.addItem("Cliente");
        jComboBox1.addItem("Genero");
        
        Text1.setVisible(true);
        
        jComboBox1.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Text1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Text2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox3 = new javax.swing.JComboBox<>();
        Text3 = new javax.swing.JLabel();
        Text4 = new javax.swing.JLabel();
        Text5 = new javax.swing.JLabel();
        Text6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text1.setForeground(new java.awt.Color(255, 255, 255));
        Text1.setText("Text1");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 180, -1));

        Text2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setText("Text2");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 180, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { }));
        add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, -1));

        Text3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text3.setForeground(new java.awt.Color(255, 255, 255));
        Text3.setText("Text3");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, 20));

        Text4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text4.setForeground(new java.awt.Color(255, 255, 255));
        Text4.setText("Text4");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 270, 20));

        Text5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text5.setForeground(new java.awt.Color(255, 255, 255));
        Text5.setText("Text5");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 270, 20));

        Text6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text6.setForeground(new java.awt.Color(255, 255, 255));
        Text6.setText("Text6");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 270, 20));

        jButton1.setBackground(new java.awt.Color(0, 204, 102));
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 540, 250));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String filtro = jComboBox1.getSelectedItem()!= null ? jComboBox1.getSelectedItem().toString() : "";
        jComboBox2.removeAllItems();
        if(filtro.equalsIgnoreCase("Cliente")){
                Text2.setText("Clientes:");
                Text2.setVisible(true);
                for (String art : ctrl.obtenerNombresClienteConParticular()){
                    jComboBox2.addItem(art);
                }
            }
        
        if(filtro.equalsIgnoreCase("Genero")){
            jComboBox2.removeAllItems();
            Text2.setText("Generos:");
            Text2.setVisible(true);
            for (String gen : ctrl.obtenerNombresDeGenerosConPorDefecto()){
                if(gen.equalsIgnoreCase("Genero")){

                    }else{
                        jComboBox2.addItem(gen);
                    }
            }    
        }
        jComboBox2.setVisible(true);
        jButton1.setVisible(true);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String filtro = jComboBox1.getSelectedItem()!= null ? jComboBox1.getSelectedItem().toString() : "";
        String filtro2 = jComboBox2.getSelectedItem()!= null ? jComboBox2.getSelectedItem().toString() : "";
        
        jComboBox3.removeAllItems();
        Text3.setText("Lista: ");
        if(filtro.equalsIgnoreCase("Cliente")){
            if(ctrl.obtenerPartPublicaDeDuenio(filtro2)!=null){
                for(String alb : ctrl.obtenerPartPublicaDeDuenio(filtro2)){
                    jComboBox3.addItem(alb);
                }
            }
        }
        
        if(filtro.equalsIgnoreCase("Genero")){
            if(ctrl.obtenerListasDeGenero(filtro2)!=null){
                for(String alb : ctrl.obtenerListasDeGenero(filtro2)){
                    jComboBox3.addItem(alb);
                }
            }
        }
        
        Text3.setVisible(true);
        jComboBox3.setVisible(true);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Cliente o Genero
        String filtro = jComboBox1.getSelectedItem()!= null ? jComboBox1.getSelectedItem().toString() : "";
        //Cliente especifico y Genero especifico
        String filtro2 = jComboBox2.getSelectedItem()!= null ? jComboBox2.getSelectedItem().toString() : "";
        
        String nombreLista = jComboBox3.getSelectedItem() != null ? jComboBox3.getSelectedItem().toString() : "";
        
        jPanel1.removeAll();
        
        if(filtro.equalsIgnoreCase("Cliente")){
            DataParticular dp = ctrl.obtenerDataParticular(nombreLista,filtro2);
            
            Text4.setText("Nombre Playlist: "+dp.getNombre());
            
            Text5.setText("Cliente creador: "+dp.getCliente());
            
            Text6.setText("Posicion || Nombre || Duracion");
            
            jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));

            for(DataTema tem : dp.getDataTemas()){
                // Crear un nuevo panel para cada tema
                JPanel info = new JPanel();
                info.setLayout(new FlowLayout(FlowLayout.LEFT));

                JLabel labelNombre = new JLabel(tem.getNombre() + " - ");
                labelNombre.setFont(new Font("Arial", Font.PLAIN, 12));
                labelNombre.setForeground(Color.BLACK);

                JLabel labelDuracion = new JLabel(tem.getDuracion() + " mins" + "  ");
                labelDuracion.setFont(new Font("Arial", Font.PLAIN, 12));
                labelDuracion.setForeground(Color.BLACK);

                JLabel labelOrden = new JLabel(tem.getOrdenAlbum() + " - ");
                labelOrden.setFont(new Font("Arial", Font.PLAIN, 12));
                labelOrden.setForeground(Color.BLACK);

                // Agregar etiquetas al panel de tema
                info.add(labelOrden); //el niño mimado pidio que modificara como se muestra
                info.add(labelNombre);
                info.add(labelDuracion);

                // Botón para abrir el archivo o URL
                    JButton botonTema = new JButton("Escuchar");
                    botonTema.addActionListener(e -> {
                        String direccion = tem.getDireccion(); 
                        if (direccion != null) {
                            try{
                                // Si es un archivo
                                File file = new File(direccion);
                                if (file.exists()) {
                                    Desktop.getDesktop().open(file);
                                } else {
                                    // si no lo encuentro en la PC o es una URL muestro un pop up
                                    JOptionPane.showMessageDialog(null, "Guardado en: "+ direccion);
                                    JOptionPane.showMessageDialog(null, "(descargar archivos Soon™\n si el archivo existe en el sistema se puede reproducir)");
                                }
                            }catch (IOException ex){
                                ex.printStackTrace();
                                JOptionPane.showMessageDialog(null, "Error al abrir el archivo: " + ex.getMessage());
                            }
                        }
                    });

                    info.add(botonTema);
                // Añadir el panel del tema al jPanel4
                jPanel1.add(info);
            }
        }
        
    if(filtro.equalsIgnoreCase("Genero")){
            DataPorDefecto dpd = ctrl.obtenerDataPorDefecto(nombreLista);

            Text4.setText("Nombre Playlist: "+dpd.getNombre());

            Text5.setText("Genero: "+dpd.getGenero());
           
            Text6.setText("Posicion || Nombre || Duracion");
            
            jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
            
            for(DataTema tem : dpd.getDataTemas()){
                // Crear un nuevo panel para cada tema
                JPanel info = new JPanel();
                info.setLayout(new FlowLayout(FlowLayout.LEFT));

                JLabel labelNombre = new JLabel(tem.getNombre() + " - ");
                labelNombre.setFont(new Font("Arial", Font.PLAIN, 12));
                labelNombre.setForeground(Color.BLACK);

                JLabel labelDuracion = new JLabel(tem.getDuracion() + " mins" + "  ");
                labelDuracion.setFont(new Font("Arial", Font.PLAIN, 12));
                labelDuracion.setForeground(Color.BLACK);

                JLabel labelOrden = new JLabel(tem.getOrdenAlbum() + " - ");
                labelOrden.setFont(new Font("Arial", Font.PLAIN, 12));
                labelOrden.setForeground(Color.BLACK);

                // Agregar etiquetas al panel de tema
                info.add(labelOrden); //el niño mimado pidio que modificara como se muestra
                info.add(labelNombre);
                info.add(labelDuracion);


                // Botón para abrir el archivo o URL
                JButton botonTema = new JButton("Escuchar");
                botonTema.addActionListener(e -> {
                    String direccion = tem.getDireccion(); 
                    if (direccion != null) {
                        try{
                            // Si es un archivo
                            File file = new File(direccion);
                            if (file.exists()) {
                                Desktop.getDesktop().open(file);
                            } else {
                                // si no lo encuentro en la PC o es una URL muestro un pop up
                                JOptionPane.showMessageDialog(null, "Guardado en:"+ direccion);
                                JOptionPane.showMessageDialog(null, "(descargar archivos Soon™\n si el archivo existe en el sistema se puede reproducir)");
                            }
                        }catch (IOException ex){
                            ex.printStackTrace();
                            JOptionPane.showMessageDialog(null, "Error al abrir el archivo:" + ex.getMessage());
                        }
                    }
                });

                info.add(botonTema);
                // Añadir el panel del tema al jPanel4
                jPanel1.add(info);
            }
            
        }
            
        Text4.setVisible(true);
        Text5.setVisible(true);
        Text6.setVisible(true);
        jPanel1.setVisible(true);
        jPanel1.revalidate();
        jPanel1.repaint();
            
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
