package Capa_Presentacion;

import Logica.Factory;
import Logica.ICtrl;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author cedre
 */
public class IConsultarPerfil extends javax.swing.JPanel {

    /**
     * Creates new form IAltaPerfil
     */
    Factory fabric =Factory.getInstance();
    ICtrl ctrl = fabric.getICtrl();
    public IConsultarPerfil() {
        initComponents();
        jButton1.setText("Consultar");
        Text1.setText("Filtro de consulta");
        jComboBox1.addItem("Artista");
        jComboBox1.addItem("Cliente");
        Text1.setVisible(true);
        Text2.setVisible(true);
        jComboBox1.setVisible(true);
        jComboBox2.setVisible(true);
        Text3.setVisible(false);
        Text4.setVisible(false);
        Text5.setVisible(false);
        Text6.setVisible(false);
        Text7.setVisible(false);
        Text8.setVisible(false);
        Text9.setVisible(false);
        Text10.setVisible(false);
        Text11.setVisible(false);
        Text12.setVisible(false);
        Text13.setVisible(false);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        Text1 = new javax.swing.JLabel();
        Text3 = new javax.swing.JLabel();
        Text4 = new javax.swing.JLabel();
        Text5 = new javax.swing.JLabel();
        Text6 = new javax.swing.JLabel();
        Text7 = new javax.swing.JLabel();
        Text8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox<>();
        Text2 = new javax.swing.JLabel();
        Text9 = new javax.swing.JLabel();
        Text10 = new javax.swing.JLabel();
        Text11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        Text12 = new javax.swing.JLabel();
        Text13 = new javax.swing.JLabel();

        jCheckBox1.setText("jCheckBox1");

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Text1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text1.setForeground(new java.awt.Color(255, 255, 255));
        Text1.setText("Text1");
        add(Text1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 6, 310, 20));

        Text3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text3.setForeground(new java.awt.Color(255, 255, 255));
        Text3.setText("Text3");
        add(Text3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 127, 310, 20));

        Text4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text4.setForeground(new java.awt.Color(255, 255, 255));
        Text4.setText("Text4");
        add(Text4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 153, 310, 20));

        Text5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text5.setForeground(new java.awt.Color(255, 255, 255));
        Text5.setText("Text5");
        add(Text5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 179, 310, 20));

        Text6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text6.setForeground(new java.awt.Color(255, 255, 255));
        Text6.setText("Text6");
        add(Text6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 269, 103, 20));

        Text7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text7.setForeground(new java.awt.Color(255, 255, 255));
        Text7.setText("Text7");
        add(Text7, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 269, 103, 20));

        Text8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text8.setForeground(new java.awt.Color(255, 255, 255));
        Text8.setText("Text8");
        add(Text8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 413, -1, 20));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {} ));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 204, 102));
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 92, -1, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 92, -1, -1));

        Text2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setText("Text2");
        add(Text2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, 310, 20));

        Text9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text9.setForeground(new java.awt.Color(255, 255, 255));
        Text9.setText("Text9");
        add(Text9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 503, 218, 20));

        Text10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text10.setForeground(new java.awt.Color(255, 255, 255));
        Text10.setText("Text10");
        add(Text10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 591, 218, 20));

        Text11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text11.setForeground(new java.awt.Color(255, 255, 255));
        Text11.setText("Text11");
        add(Text11, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 269, -1, 20));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 295, 103, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 103, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 106, Short.MAX_VALUE)
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 295, 103, -1));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 439, 218, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 529, 218, -1));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 218, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
        );

        add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 617, 218, -1));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 231, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(246, 295, -1, -1));

        Text12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text12.setForeground(new java.awt.Color(255, 255, 255));
        Text12.setText("Text12");
        add(Text12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, -1, 20));

        Text13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text13.setForeground(new java.awt.Color(255, 255, 255));
        Text13.setText("Text13");
        add(Text13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, -1, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String selectedItem = jComboBox1.getSelectedItem().toString();
        if(selectedItem.equals("Artista")){
            jComboBox2.removeAllItems();
            Text2.setText("Elija un Artista");
            for (String Part : ctrl.obtenerNombresDeArtista()) {
                jComboBox2.addItem(Part);
            }
        }else{
            jComboBox2.removeAllItems();
            Text2.setText("Elija un Cliente");
            for (String Part : ctrl.obtenerNombresDeCliente()) {
                jComboBox2.addItem(Part);
            }
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
        Object selectedItem = jComboBox2.getSelectedItem();
        if (selectedItem != null && !selectedItem.toString().isEmpty()) {
            String selectedText = selectedItem.toString();
            System.out.println("Selected item: " + selectedText);
            // Utiliza selectedText según sea necesario
        } else {
            System.out.println("No item selected or item is empty.");
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nick = jComboBox2.getSelectedItem().toString();
        
        Text3.setVisible(false);
        Text4.setVisible(false);
        Text5.setVisible(false);
        Text6.setVisible(false);
        Text7.setVisible(false);
        Text8.setVisible(false);
        Text9.setVisible(false);
        Text10.setVisible(false);
        Text11.setVisible(false);
        Text12.setVisible(false);
        Text13.setVisible(false);
        jPanel1.setVisible(false);
        jPanel2.setVisible(false);
        jPanel3.setVisible(false);
        jPanel4.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        
        if(jComboBox1.getSelectedItem().toString().equals("Cliente")){
            Text3.setText("Nombre: "+ctrl.nombreCliente(nick));
            Text3.setVisible(true);
            Text4.setText("Apellido: "+ctrl.apellidoCliente(nick));
            Text4.setVisible(true);
            Text5.setText("Correo: "+ctrl.mailCliente(nick));
            Text5.setVisible(true);
            Text12.setText("Nacimiento: "+ctrl.fechaCliente(nick));
            Text12.setVisible(true);
            Text6.setText("Seguidos");
            Text6.setVisible(true);
            Text7.setText("Seguidores");
            Text7.setVisible(true);
            Text8.setText("Playlists");
            Text8.setVisible(true);
            Text9.setText("Temas Favoritos");
            Text9.setVisible(true);
            Text10.setText("Albumes Favoritos");
            Text10.setVisible(true);
            Text11.setText("Listas favoritas");
            Text11.setVisible(true);
            
            //seguidores
            jPanel1.removeAll();
            jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
            for(String dato : ctrl.listaSeguidoresCliente(nick)){
                JLabel labelNombre = new JLabel(dato);
                labelNombre.setFont(new Font("Arial", Font.PLAIN, 12));
                labelNombre.setForeground(Color.BLACK);
                jPanel1.add(labelNombre);
            }
            jPanel1.setVisible(true);
            
            //seguidos
            jPanel2.removeAll();
            jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
            for(String dato : ctrl.listaSeguidosCliente(nick)){
                JLabel labelNombre = new JLabel(dato);
                labelNombre.setFont(new Font("Arial", Font.PLAIN, 12));
                labelNombre.setForeground(Color.BLACK);
                jPanel2.add(labelNombre);
            }
            jPanel2.setVisible(true);
            
            //Playlists
            jPanel3.removeAll();
            jPanel3.setLayout(new BoxLayout(jPanel3, BoxLayout.Y_AXIS));
            for(String dato : ctrl.listaPlaylistCliente(nick)){
                JLabel labelNombre = new JLabel(dato);
                labelNombre.setFont(new Font("Arial", Font.PLAIN, 12));
                labelNombre.setForeground(Color.BLACK);
                jPanel3.add(labelNombre);
            }
            jPanel3.setVisible(true);
            
            //TemasFAV
            jPanel4.removeAll();
            jPanel4.setLayout(new BoxLayout(jPanel4, BoxLayout.Y_AXIS));
            for(String dato : ctrl.listaTemasFavCliente(nick)){
                JLabel labelNombre = new JLabel(dato);
                labelNombre.setFont(new Font("Arial", Font.PLAIN, 12));
                labelNombre.setForeground(Color.BLACK);
                jPanel4.add(labelNombre);
            }
            jPanel4.setVisible(true);
            
            //AlbumesFAV
            jPanel5.removeAll();
            jPanel5.setLayout(new BoxLayout(jPanel5, BoxLayout.Y_AXIS));
            for(String dato : ctrl.listaAlbumFavCliente(nick)){
                JLabel labelNombre = new JLabel(dato);
                labelNombre.setFont(new Font("Arial", Font.PLAIN, 12));
                labelNombre.setForeground(Color.BLACK);
                jPanel5.add(labelNombre);
            }
            jPanel5.setVisible(true);
            
            //ListasFAV
            jPanel6.removeAll();
            jPanel6.setLayout(new BoxLayout(jPanel6, BoxLayout.Y_AXIS));
            for(String dato : ctrl.listaPlaylistFavCliente(nick)){
                JLabel labelNombre = new JLabel(dato);
                labelNombre.setFont(new Font("Arial", Font.PLAIN, 12));
                labelNombre.setForeground(Color.BLACK);
                jPanel6.add(labelNombre);
            }
            jPanel6.setVisible(true);
        }else{
            Text3.setText("Nombre: "+ctrl.nombreArtista(nick));
            Text3.setVisible(true);
            Text4.setText("Apellido: "+ctrl.apellidoArtista(nick));
            Text4.setVisible(true);
            Text5.setText("Correo: "+ctrl.mailArtista(nick));
            Text5.setVisible(true);
            Text12.setText("Nacimiento: "+ctrl.fechaArtista(nick));
            Text12.setVisible(true);
            Text13.setText("Pagina Web: "+ctrl.webArtista(nick));
            Text13.setVisible(true);
            Text6.setText("Seguidores ("+ctrl.cantSeguidoresArtista(nick)+")");
            Text6.setVisible(true);
            Text7.setText("Albumes");
            Text7.setVisible(true);
            Text11.setText("Biografía");
            Text11.setVisible(true);
            
            jPanel1.removeAll();
            jPanel1.setLayout(new BoxLayout(jPanel1, BoxLayout.Y_AXIS));
            for(String dato : ctrl.listaSeguidoresArtista(nick)){
                JLabel labelNombre = new JLabel(dato);
                labelNombre.setFont(new Font("Arial", Font.PLAIN, 12));
                labelNombre.setForeground(Color.BLACK);
                jPanel1.add(labelNombre);
            }
            jPanel1.setVisible(true);
            
            jPanel2.removeAll();
            jPanel2.setLayout(new BoxLayout(jPanel2, BoxLayout.Y_AXIS));
            for(String dato : ctrl.listaAlbumArtista(nick)){
                JLabel labelNombre = new JLabel(dato);
                labelNombre.setFont(new Font("Arial", Font.PLAIN, 12));
                labelNombre.setForeground(Color.BLACK);
                jPanel2.add(labelNombre);
            }
            jPanel2.setVisible(true);
            
            jPanel6.removeAll();
            jPanel6.setLayout(new BoxLayout(jPanel6, BoxLayout.Y_AXIS));
            String bioArtista = "<html><body style='width: 200px;'>" + ctrl.bioArtista(nick) + "</body></html>";
            JLabel labelNombre = new JLabel(bioArtista);
            labelNombre.setFont(new Font("Arial", Font.PLAIN, 12));
            labelNombre.setForeground(Color.BLACK);
            jPanel6.add(labelNombre);
            
            jPanel6.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text10;
    private javax.swing.JLabel Text11;
    private javax.swing.JLabel Text12;
    private javax.swing.JLabel Text13;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JLabel Text5;
    private javax.swing.JLabel Text6;
    private javax.swing.JLabel Text7;
    private javax.swing.JLabel Text8;
    private javax.swing.JLabel Text9;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    // End of variables declaration//GEN-END:variables
}
