package Capa_Presentacion;

import Logica.Factory;
import Logica.ICtrl;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author cedre
 */
public class ICrearLista extends javax.swing.JPanel {

    /**
     * Creates new form IAltaPerfil
     */
        Factory fabric =Factory.getInstance();
	ICtrl ctrl = fabric.getICtrl();
    
        public ICrearLista() {
        initComponents();
        Text1.setText("Nombre de Lista*");
        Text2.setText("Tipo");
        Text4.setText("");
        TextField1.setText("");
        jComboBox1.addItem("Particular");
        jComboBox1.addItem("Por Defecto");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ACEPTAR = new javax.swing.JButton();
        TextField1 = new javax.swing.JTextField();
        Text1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        Text2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Text3 = new javax.swing.JLabel();
        Text4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));

        ACEPTAR.setBackground(new java.awt.Color(0, 204, 102));
        ACEPTAR.setText("ACEPTAR");
        ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPTARActionPerformed(evt);
            }
        });

        TextField1.setBackground(new java.awt.Color(102, 102, 102));
        TextField1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        TextField1.setForeground(new java.awt.Color(255, 255, 255));
        TextField1.setText("TextField1");
        TextField1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField1ActionPerformed(evt);
            }
        });

        Text1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text1.setForeground(new java.awt.Color(255, 255, 255));
        Text1.setText("Text1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        Text2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text2.setForeground(new java.awt.Color(255, 255, 255));
        Text2.setText("Text2");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {  }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        Text3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text3.setForeground(new java.awt.Color(255, 255, 255));
        Text3.setText("Text3");

        Text4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Text4.setForeground(new java.awt.Color(255, 255, 255));
        Text4.setText("Text4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Text3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(182, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Text4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ACEPTAR)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Text1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Text2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addComponent(Text3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 371, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACEPTAR)
                    .addComponent(Text4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
         Object selectedItem = jComboBox1.getSelectedItem();
        if("Particular".equals(selectedItem)){
            Text3.setText("Clientes");
            if(jComboBox2.getItemCount() > 0){
                jComboBox2.removeAllItems();
            }
            //Agregar nombres de los clientes
            for (String cli : ctrl.obtenerNombresDeCliente()) {
                    jComboBox2.addItem(cli);
            }
        }else{
            Text3.setText("Generos");
            if(jComboBox2.getItemCount() > 0){
                jComboBox2.removeAllItems();
            }
            //Agregar nombres de los Generos
            for (String genero : ctrl.obtenerNombresDeGeneros()) {
                if(!"Genero".equals(genero)){
                    jComboBox2.addItem(genero);
                }
            }
        }                                
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTARActionPerformed
        // TODO add your handling code here:
        String NomList = TextField1.getText();
        Object selectedItem = jComboBox1.getSelectedItem();
        String GoC =  jComboBox2.getSelectedItem().toString();//Genero o Cliente
        boolean PuedoCrear = false;
        if("Particular".equals(selectedItem)){
            if(ctrl.ExisListPartEnCliente(NomList, GoC)==true){//Si es true quiere decir que existe por ende no puedo crearla
            Text4.setText("Ya existe una lista con ese nombre");
            Text4.setVisible(true);
            }else{
                PuedoCrear=true;//Si no existe si puedo crearla            
            }
        }else{
            if(ctrl.ExisListPorDefEnGenero(NomList)==true){
                Text4.setText("Ya existe una lista con ese nombre");
                Text4.setVisible(true);
            }else{
                PuedoCrear=true;//Si no existe si puedo crearla 
            }
        }
        if(TextField1.getText().equals("")){
            Text4.setVisible(false);
            Text4.setText("Ingrese un Nombre a la Lista");
            Text4.setVisible(true);
        }else{
            if(PuedoCrear==true){
                //CrearLista
                if("Particular".equals(selectedItem)){
                    ctrl.CrearListParticular(NomList, GoC);
                }else{
                    ctrl.CrearListPorDefecto(NomList, GoC);
                }
               Text4.setVisible(false);
               Text4.setText("Lista creada con exito");
               Text4.setVisible(true);
            }
         }
    }//GEN-LAST:event_ACEPTARActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.JLabel Text1;
    private javax.swing.JLabel Text2;
    private javax.swing.JLabel Text3;
    private javax.swing.JLabel Text4;
    private javax.swing.JTextField TextField1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    // End of variables declaration//GEN-END:variables
}
